
version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: urnm1/cxx-dev-env:3.10
    steps:
      - checkout
      - run:
          name: configure
          command: |
            cmake --configure .
      - run:
          name: build
          command: |
            cmake --build .
